services:
  - type: web
    name: 99-idea-puzzle
    env: node
    region: oregon
    plan: free
    buildCommand: npm install --prefix Game
    startCommand: cd Game && node server.js
    envVars:
      - key: NODE_ENV
        value: production
